services:
  db:
    image: "postgres:16" # use the latest postgres image
    environment:
      - POSTGRES_PASSWORD=Steven12 # password for the user
      - POSTGRES_USER=steven # name of the user
      - POSTGRES_DB=shelter # name of the database
    volumes:
      - db_data:/var/lib/postgresql/data # to persist data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # to run init script
    ports:
      - "5432:5432" # expose port 5432 to the host

  etl:
    build: . # build the image from the current directory
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db 

volumes:
  db_data:



